// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proto/search.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Search struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                      *uint32                         `protobuf:"varint,1,req,name=Id,json=id" json:"Id,omitempty"`
	Location                *Search_Location                `protobuf:"bytes,2,req,name=location" json:"location,omitempty"`
	OutdoorDesignConditions *Search_Outdoordesignconditions `protobuf:"bytes,3,req,name=outdoorDesignConditions" json:"outdoorDesignConditions,omitempty"`
	IndoorDesignConditions  *Search_Indoordesignconditions  `protobuf:"bytes,4,req,name=indoorDesignConditions" json:"indoorDesignConditions,omitempty"`
	NominalSize             *Search_NominalSize             `protobuf:"bytes,5,opt,name=nominalSize" json:"nominalSize,omitempty"`
	LoadCalculation         *Search_Loadcalculation         `protobuf:"bytes,6,opt,name=loadCalculation" json:"loadCalculation,omitempty"`
	SystemAttributes        *Search_Systemattributes        `protobuf:"bytes,7,req,name=systemAttributes" json:"systemAttributes,omitempty"`
}

func (x *Search) Reset() {
	*x = Search{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Search) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search) ProtoMessage() {}

func (x *Search) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search.ProtoReflect.Descriptor instead.
func (*Search) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0}
}

func (x *Search) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Search) GetLocation() *Search_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Search) GetOutdoorDesignConditions() *Search_Outdoordesignconditions {
	if x != nil {
		return x.OutdoorDesignConditions
	}
	return nil
}

func (x *Search) GetIndoorDesignConditions() *Search_Indoordesignconditions {
	if x != nil {
		return x.IndoorDesignConditions
	}
	return nil
}

func (x *Search) GetNominalSize() *Search_NominalSize {
	if x != nil {
		return x.NominalSize
	}
	return nil
}

func (x *Search) GetLoadCalculation() *Search_Loadcalculation {
	if x != nil {
		return x.LoadCalculation
	}
	return nil
}

func (x *Search) GetSystemAttributes() *Search_Systemattributes {
	if x != nil {
		return x.SystemAttributes
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoolingCapacity    *int32   `protobuf:"varint,1,req,name=CoolingCapacity,json=coolingCapacity" json:"CoolingCapacity,omitempty"`
	EER                *float64 `protobuf:"fixed64,2,req,name=EER,json=eer" json:"EER,omitempty"`
	SEER               *float64 `protobuf:"fixed64,3,req,name=SEER,json=seer" json:"SEER,omitempty"`
	HSPF               *float64 `protobuf:"fixed64,4,opt,name=HSPF,json=hspf" json:"HSPF,omitempty"`
	AFUE               *float64 `protobuf:"fixed64,5,req,name=AFUE,json=afue" json:"AFUE,omitempty"`
	OutdoorUnitSKU     *string  `protobuf:"bytes,6,req,name=OutdoorUnitSKU,json=outdoorUnitSKU" json:"OutdoorUnitSKU,omitempty"`
	IndoorUnitSKU      *string  `protobuf:"bytes,7,req,name=IndoorUnitSKU,json=indoorUnitSKU" json:"IndoorUnitSKU,omitempty"`
	FurnaceSKU         *string  `protobuf:"bytes,8,req,name=FurnaceSKU,json=furnaceSKU" json:"FurnaceSKU,omitempty"`
	NominalCoolingTons *float64 `protobuf:"fixed64,9,opt,name=NominalCoolingTons,json=nominalCoolingTons" json:"NominalCoolingTons,omitempty"`
	SensibleCapacity   *int32   `protobuf:"varint,10,opt,name=SensibleCapacity,json=sensibleCapacity" json:"SensibleCapacity,omitempty"`
	LatentCapacity     *int32   `protobuf:"varint,11,opt,name=LatentCapacity,json=latentCapacity" json:"LatentCapacity,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetCoolingCapacity() int32 {
	if x != nil && x.CoolingCapacity != nil {
		return *x.CoolingCapacity
	}
	return 0
}

func (x *Result) GetEER() float64 {
	if x != nil && x.EER != nil {
		return *x.EER
	}
	return 0
}

func (x *Result) GetSEER() float64 {
	if x != nil && x.SEER != nil {
		return *x.SEER
	}
	return 0
}

func (x *Result) GetHSPF() float64 {
	if x != nil && x.HSPF != nil {
		return *x.HSPF
	}
	return 0
}

func (x *Result) GetAFUE() float64 {
	if x != nil && x.AFUE != nil {
		return *x.AFUE
	}
	return 0
}

func (x *Result) GetOutdoorUnitSKU() string {
	if x != nil && x.OutdoorUnitSKU != nil {
		return *x.OutdoorUnitSKU
	}
	return ""
}

func (x *Result) GetIndoorUnitSKU() string {
	if x != nil && x.IndoorUnitSKU != nil {
		return *x.IndoorUnitSKU
	}
	return ""
}

func (x *Result) GetFurnaceSKU() string {
	if x != nil && x.FurnaceSKU != nil {
		return *x.FurnaceSKU
	}
	return ""
}

func (x *Result) GetNominalCoolingTons() float64 {
	if x != nil && x.NominalCoolingTons != nil {
		return *x.NominalCoolingTons
	}
	return 0
}

func (x *Result) GetSensibleCapacity() int32 {
	if x != nil && x.SensibleCapacity != nil {
		return *x.SensibleCapacity
	}
	return 0
}

func (x *Result) GetLatentCapacity() int32 {
	if x != nil && x.LatentCapacity != nil {
		return *x.LatentCapacity
	}
	return 0
}

type Search_Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  *float64 `protobuf:"fixed64,1,req,name=latitude" json:"latitude,omitempty"`
	Longitude *float64 `protobuf:"fixed64,2,req,name=longitude" json:"longitude,omitempty"`
	Elevation *uint32  `protobuf:"varint,3,req,name=elevation" json:"elevation,omitempty"`
}

func (x *Search_Location) Reset() {
	*x = Search_Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Search_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Location) ProtoMessage() {}

func (x *Search_Location) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Location.ProtoReflect.Descriptor instead.
func (*Search_Location) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Search_Location) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Search_Location) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *Search_Location) GetElevation() uint32 {
	if x != nil && x.Elevation != nil {
		return *x.Elevation
	}
	return 0
}

type Search_Outdoordesignconditions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeatherStation *string  `protobuf:"bytes,1,req,name=weatherStation" json:"weatherStation,omitempty"`
	State          *string  `protobuf:"bytes,2,req,name=state" json:"state,omitempty"`
	Elevation      *uint32  `protobuf:"varint,3,req,name=elevation" json:"elevation,omitempty"`
	Latitude       *float64 `protobuf:"fixed64,4,req,name=latitude" json:"latitude,omitempty"`
	Heating99DB    *uint32  `protobuf:"varint,5,req,name=heating99DB" json:"heating99DB,omitempty"`
	Cooling01DB    *uint32  `protobuf:"varint,6,req,name=cooling01DB" json:"cooling01DB,omitempty"`
	CoincidentWB   *uint32  `protobuf:"varint,7,req,name=coincidentWB" json:"coincidentWB,omitempty"`
	DG45RH         *uint32  `protobuf:"varint,8,req,name=DG45RH" json:"DG45RH,omitempty"`
	DG50RH         *uint32  `protobuf:"varint,9,req,name=DG50RH" json:"DG50RH,omitempty"`
	DG55RH         *uint32  `protobuf:"varint,10,req,name=DG55RH" json:"DG55RH,omitempty"`
	DailyRange     *string  `protobuf:"bytes,11,req,name=dailyRange" json:"dailyRange,omitempty"`
}

func (x *Search_Outdoordesignconditions) Reset() {
	*x = Search_Outdoordesignconditions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Search_Outdoordesignconditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Outdoordesignconditions) ProtoMessage() {}

func (x *Search_Outdoordesignconditions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Outdoordesignconditions.ProtoReflect.Descriptor instead.
func (*Search_Outdoordesignconditions) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Search_Outdoordesignconditions) GetWeatherStation() string {
	if x != nil && x.WeatherStation != nil {
		return *x.WeatherStation
	}
	return ""
}

func (x *Search_Outdoordesignconditions) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *Search_Outdoordesignconditions) GetElevation() uint32 {
	if x != nil && x.Elevation != nil {
		return *x.Elevation
	}
	return 0
}

func (x *Search_Outdoordesignconditions) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Search_Outdoordesignconditions) GetHeating99DB() uint32 {
	if x != nil && x.Heating99DB != nil {
		return *x.Heating99DB
	}
	return 0
}

func (x *Search_Outdoordesignconditions) GetCooling01DB() uint32 {
	if x != nil && x.Cooling01DB != nil {
		return *x.Cooling01DB
	}
	return 0
}

func (x *Search_Outdoordesignconditions) GetCoincidentWB() uint32 {
	if x != nil && x.CoincidentWB != nil {
		return *x.CoincidentWB
	}
	return 0
}

func (x *Search_Outdoordesignconditions) GetDG45RH() uint32 {
	if x != nil && x.DG45RH != nil {
		return *x.DG45RH
	}
	return 0
}

func (x *Search_Outdoordesignconditions) GetDG50RH() uint32 {
	if x != nil && x.DG50RH != nil {
		return *x.DG50RH
	}
	return 0
}

func (x *Search_Outdoordesignconditions) GetDG55RH() uint32 {
	if x != nil && x.DG55RH != nil {
		return *x.DG55RH
	}
	return 0
}

func (x *Search_Outdoordesignconditions) GetDailyRange() string {
	if x != nil && x.DailyRange != nil {
		return *x.DailyRange
	}
	return ""
}

type Search_Indoordesignconditions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinterIndoorF *uint32 `protobuf:"varint,1,req,name=winterIndoorF" json:"winterIndoorF,omitempty"`
	SummerIndoorF *uint32 `protobuf:"varint,2,req,name=summerIndoorF" json:"summerIndoorF,omitempty"`
	CoolingRH     *uint32 `protobuf:"varint,3,req,name=coolingRH" json:"coolingRH,omitempty"`
}

func (x *Search_Indoordesignconditions) Reset() {
	*x = Search_Indoordesignconditions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Search_Indoordesignconditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Indoordesignconditions) ProtoMessage() {}

func (x *Search_Indoordesignconditions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Indoordesignconditions.ProtoReflect.Descriptor instead.
func (*Search_Indoordesignconditions) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Search_Indoordesignconditions) GetWinterIndoorF() uint32 {
	if x != nil && x.WinterIndoorF != nil {
		return *x.WinterIndoorF
	}
	return 0
}

func (x *Search_Indoordesignconditions) GetSummerIndoorF() uint32 {
	if x != nil && x.SummerIndoorF != nil {
		return *x.SummerIndoorF
	}
	return 0
}

func (x *Search_Indoordesignconditions) GetCoolingRH() uint32 {
	if x != nil && x.CoolingRH != nil {
		return *x.CoolingRH
	}
	return 0
}

type Search_NominalSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NominalTons *float64 `protobuf:"fixed64,1,req,name=nominalTons" json:"nominalTons,omitempty"`
	HeatingBTUH *float64 `protobuf:"fixed64,2,req,name=heatingBTUH" json:"heatingBTUH,omitempty"`
}

func (x *Search_NominalSize) Reset() {
	*x = Search_NominalSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Search_NominalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_NominalSize) ProtoMessage() {}

func (x *Search_NominalSize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_NominalSize.ProtoReflect.Descriptor instead.
func (*Search_NominalSize) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Search_NominalSize) GetNominalTons() float64 {
	if x != nil && x.NominalTons != nil {
		return *x.NominalTons
	}
	return 0
}

func (x *Search_NominalSize) GetHeatingBTUH() float64 {
	if x != nil && x.HeatingBTUH != nil {
		return *x.HeatingBTUH
	}
	return 0
}

type Search_Loadcalculation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensibleBTUH *float64 `protobuf:"fixed64,1,req,name=sensibleBTUH" json:"sensibleBTUH,omitempty"`
	HeatingBTUH  *float64 `protobuf:"fixed64,2,req,name=heatingBTUH" json:"heatingBTUH,omitempty"`
	LatentBTUH   *float64 `protobuf:"fixed64,3,req,name=latentBTUH" json:"latentBTUH,omitempty"`
}

func (x *Search_Loadcalculation) Reset() {
	*x = Search_Loadcalculation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Search_Loadcalculation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Loadcalculation) ProtoMessage() {}

func (x *Search_Loadcalculation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Loadcalculation.ProtoReflect.Descriptor instead.
func (*Search_Loadcalculation) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Search_Loadcalculation) GetSensibleBTUH() float64 {
	if x != nil && x.SensibleBTUH != nil {
		return *x.SensibleBTUH
	}
	return 0
}

func (x *Search_Loadcalculation) GetHeatingBTUH() float64 {
	if x != nil && x.HeatingBTUH != nil {
		return *x.HeatingBTUH
	}
	return 0
}

func (x *Search_Loadcalculation) GetLatentBTUH() float64 {
	if x != nil && x.LatentBTUH != nil {
		return *x.LatentBTUH
	}
	return 0
}

type Search_Heatedcooled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProvidesCooling *bool `protobuf:"varint,1,req,name=providesCooling" json:"providesCooling,omitempty"`
	ProvidesHeating *bool `protobuf:"varint,2,req,name=providesHeating" json:"providesHeating,omitempty"`
}

func (x *Search_Heatedcooled) Reset() {
	*x = Search_Heatedcooled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Search_Heatedcooled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Heatedcooled) ProtoMessage() {}

func (x *Search_Heatedcooled) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Heatedcooled.ProtoReflect.Descriptor instead.
func (*Search_Heatedcooled) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Search_Heatedcooled) GetProvidesCooling() bool {
	if x != nil && x.ProvidesCooling != nil {
		return *x.ProvidesCooling
	}
	return false
}

func (x *Search_Heatedcooled) GetProvidesHeating() bool {
	if x != nil && x.ProvidesHeating != nil {
		return *x.ProvidesHeating
	}
	return false
}

type Search_Systemattributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeatedCooled             *Search_Heatedcooled `protobuf:"bytes,1,opt,name=heatedCooled" json:"heatedCooled,omitempty"`
	FuelSource               *string              `protobuf:"bytes,2,req,name=fuelSource" json:"fuelSource,omitempty"`
	EnergyDistributionMethod *string              `protobuf:"bytes,3,req,name=energyDistributionMethod" json:"energyDistributionMethod,omitempty"`
}

func (x *Search_Systemattributes) Reset() {
	*x = Search_Systemattributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_search_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Search_Systemattributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Search_Systemattributes) ProtoMessage() {}

func (x *Search_Systemattributes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Search_Systemattributes.ProtoReflect.Descriptor instead.
func (*Search_Systemattributes) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Search_Systemattributes) GetHeatedCooled() *Search_Heatedcooled {
	if x != nil {
		return x.HeatedCooled
	}
	return nil
}

func (x *Search_Systemattributes) GetFuelSource() string {
	if x != nil && x.FuelSource != nil {
		return *x.FuelSource
	}
	return ""
}

func (x *Search_Systemattributes) GetEnergyDistributionMethod() string {
	if x != nil && x.EnergyDistributionMethod != nil {
		return *x.EnergyDistributionMethod
	}
	return ""
}

var File_proto_search_proto protoreflect.FileDescriptor

var file_proto_search_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x68, 0x72, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22,
	0xa7, 0x0c, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61,
	0x68, 0x72, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x63, 0x0a, 0x17, 0x6f, 0x75, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x44, 0x65, 0x73,
	0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x68, 0x72, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x4f, 0x75, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x64, 0x65,
	0x73, 0x69, 0x67, 0x6e, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x17,
	0x6f, 0x75, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x44, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x60, 0x0a, 0x16, 0x69, 0x6e, 0x64, 0x6f, 0x6f,
	0x72, 0x44, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x68, 0x72, 0x69, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x49, 0x6e, 0x64, 0x6f, 0x6f,
	0x72, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x16, 0x69, 0x6e, 0x64, 0x6f, 0x6f, 0x72, 0x44, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d,
	0x69, 0x6e, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x61, 0x68, 0x72, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x2e, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x0b, 0x6e,
	0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x4b, 0x0a, 0x0f, 0x6c, 0x6f,
	0x61, 0x64, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x68, 0x72, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4e, 0x0a, 0x10, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x02, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x61, 0x68, 0x72, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x10, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x1a, 0x62, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d,
	0x52, 0x09, 0x65, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0xe1, 0x02, 0x0a, 0x17,
	0x4f, 0x75, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x63, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x77, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x0e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6c, 0x65, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x6c, 0x65, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x02, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x68, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x39, 0x39, 0x44, 0x42, 0x18, 0x05,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x0b, 0x68, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x39, 0x39, 0x44,
	0x42, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x30, 0x31, 0x44, 0x42,
	0x18, 0x06, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x30,
	0x31, 0x44, 0x42, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x57, 0x42, 0x18, 0x07, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f, 0x69, 0x6e, 0x63,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x57, 0x42, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x47, 0x34, 0x35, 0x52,
	0x48, 0x18, 0x08, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x44, 0x47, 0x34, 0x35, 0x52, 0x48, 0x12,
	0x16, 0x0a, 0x06, 0x44, 0x47, 0x35, 0x30, 0x52, 0x48, 0x18, 0x09, 0x20, 0x02, 0x28, 0x0d, 0x52,
	0x06, 0x44, 0x47, 0x35, 0x30, 0x52, 0x48, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x47, 0x35, 0x35, 0x52,
	0x48, 0x18, 0x0a, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x44, 0x47, 0x35, 0x35, 0x52, 0x48, 0x12,
	0x1e, 0x0a, 0x0a, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x0b, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x1a,
	0x82, 0x01, 0x0a, 0x16, 0x49, 0x6e, 0x64, 0x6f, 0x6f, 0x72, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e,
	0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x77, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x6f, 0x6f, 0x72, 0x46, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x0d, 0x52, 0x0d, 0x77, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x6f, 0x6f, 0x72, 0x46,
	0x12, 0x24, 0x0a, 0x0d, 0x73, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x6f, 0x6f, 0x72,
	0x46, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0d, 0x73, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x49,
	0x6e, 0x64, 0x6f, 0x6f, 0x72, 0x46, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6f, 0x6c, 0x69, 0x6e,
	0x67, 0x52, 0x48, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x6f, 0x6f, 0x6c, 0x69,
	0x6e, 0x67, 0x52, 0x48, 0x1a, 0x51, 0x0a, 0x0b, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x01, 0x52, 0x0b, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61,
	0x6c, 0x54, 0x6f, 0x6e, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x42, 0x54, 0x55, 0x48, 0x18, 0x02, 0x20, 0x02, 0x28, 0x01, 0x52, 0x0b, 0x68, 0x65, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x42, 0x54, 0x55, 0x48, 0x1a, 0x77, 0x0a, 0x0f, 0x4c, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65,
	0x6e, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x42, 0x54, 0x55, 0x48, 0x18, 0x01, 0x20, 0x02, 0x28, 0x01,
	0x52, 0x0c, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x42, 0x54, 0x55, 0x48, 0x12, 0x20,
	0x0a, 0x0b, 0x68, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x54, 0x55, 0x48, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x01, 0x52, 0x0b, 0x68, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x54, 0x55, 0x48,
	0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x54, 0x55, 0x48, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x01, 0x52, 0x0a, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x54, 0x55, 0x48,
	0x1a, 0x62, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x74, 0x65, 0x64, 0x63, 0x6f, 0x6f, 0x6c, 0x65, 0x64,
	0x12, 0x28, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x73, 0x43, 0x6f, 0x6f, 0x6c,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x73, 0x43, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x73, 0x48, 0x65, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x08, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x73, 0x48, 0x65, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x1a, 0xb2, 0x01, 0x0a, 0x10, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x0c, 0x68, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x43, 0x6f, 0x6f, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x61, 0x68, 0x72, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x2e, 0x48, 0x65, 0x61, 0x74, 0x65, 0x64, 0x63, 0x6f, 0x6f, 0x6c, 0x65, 0x64, 0x52,
	0x0c, 0x68, 0x65, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6f, 0x6c, 0x65, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x66, 0x75, 0x65, 0x6c, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x0a, 0x66, 0x75, 0x65, 0x6c, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x3a, 0x0a,
	0x18, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x18, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0xf2, 0x02, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x43,
	0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0f, 0x63,
	0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x45, 0x45, 0x52, 0x18, 0x02, 0x20, 0x02, 0x28, 0x01, 0x52, 0x03, 0x65, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x45, 0x45, 0x52, 0x18, 0x03, 0x20, 0x02, 0x28, 0x01, 0x52, 0x04,
	0x73, 0x65, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x53, 0x50, 0x46, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x04, 0x68, 0x73, 0x70, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x46, 0x55, 0x45,
	0x18, 0x05, 0x20, 0x02, 0x28, 0x01, 0x52, 0x04, 0x61, 0x66, 0x75, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x4f, 0x75, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x53, 0x4b, 0x55, 0x18, 0x06,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x75, 0x74, 0x64, 0x6f, 0x6f, 0x72, 0x55, 0x6e, 0x69,
	0x74, 0x53, 0x4b, 0x55, 0x12, 0x24, 0x0a, 0x0d, 0x49, 0x6e, 0x64, 0x6f, 0x6f, 0x72, 0x55, 0x6e,
	0x69, 0x74, 0x53, 0x4b, 0x55, 0x18, 0x07, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x64,
	0x6f, 0x6f, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x53, 0x4b, 0x55, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x75,
	0x72, 0x6e, 0x61, 0x63, 0x65, 0x53, 0x4b, 0x55, 0x18, 0x08, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0a,
	0x66, 0x75, 0x72, 0x6e, 0x61, 0x63, 0x65, 0x53, 0x4b, 0x55, 0x12, 0x2e, 0x0a, 0x12, 0x4e, 0x6f,
	0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x43, 0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x6e, 0x73,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x12, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x43,
	0x6f, 0x6f, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x53, 0x65,
	0x6e, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x43, 0x61,
	0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x74,
	0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x6c, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x32, 0x4c,
	0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3b, 0x0a, 0x0f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x11, 0x2e, 0x61, 0x68, 0x72, 0x69, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x1a, 0x11, 0x2e, 0x61, 0x68, 0x72, 0x69, 0x5f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_proto_search_proto_rawDescOnce sync.Once
	file_proto_search_proto_rawDescData = file_proto_search_proto_rawDesc
)

func file_proto_search_proto_rawDescGZIP() []byte {
	file_proto_search_proto_rawDescOnce.Do(func() {
		file_proto_search_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_search_proto_rawDescData)
	})
	return file_proto_search_proto_rawDescData
}

var file_proto_search_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_search_proto_goTypes = []interface{}{
	(*Search)(nil),                         // 0: ahri_grpc.Search
	(*Result)(nil),                         // 1: ahri_grpc.Result
	(*Search_Location)(nil),                // 2: ahri_grpc.Search.Location
	(*Search_Outdoordesignconditions)(nil), // 3: ahri_grpc.Search.Outdoordesignconditions
	(*Search_Indoordesignconditions)(nil),  // 4: ahri_grpc.Search.Indoordesignconditions
	(*Search_NominalSize)(nil),             // 5: ahri_grpc.Search.NominalSize
	(*Search_Loadcalculation)(nil),         // 6: ahri_grpc.Search.Loadcalculation
	(*Search_Heatedcooled)(nil),            // 7: ahri_grpc.Search.Heatedcooled
	(*Search_Systemattributes)(nil),        // 8: ahri_grpc.Search.Systemattributes
}
var file_proto_search_proto_depIdxs = []int32{
	2, // 0: ahri_grpc.Search.location:type_name -> ahri_grpc.Search.Location
	3, // 1: ahri_grpc.Search.outdoorDesignConditions:type_name -> ahri_grpc.Search.Outdoordesignconditions
	4, // 2: ahri_grpc.Search.indoorDesignConditions:type_name -> ahri_grpc.Search.Indoordesignconditions
	5, // 3: ahri_grpc.Search.nominalSize:type_name -> ahri_grpc.Search.NominalSize
	6, // 4: ahri_grpc.Search.loadCalculation:type_name -> ahri_grpc.Search.Loadcalculation
	8, // 5: ahri_grpc.Search.systemAttributes:type_name -> ahri_grpc.Search.Systemattributes
	7, // 6: ahri_grpc.Search.Systemattributes.heatedCooled:type_name -> ahri_grpc.Search.Heatedcooled
	0, // 7: ahri_grpc.SearchService.EquipmentSearch:input_type -> ahri_grpc.Search
	1, // 8: ahri_grpc.SearchService.EquipmentSearch:output_type -> ahri_grpc.Result
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_search_proto_init() }
func file_proto_search_proto_init() {
	if File_proto_search_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_search_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Search); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Search_Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Search_Outdoordesignconditions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Search_Indoordesignconditions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Search_NominalSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Search_Loadcalculation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Search_Heatedcooled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_search_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Search_Systemattributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_search_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_proto_goTypes,
		DependencyIndexes: file_proto_search_proto_depIdxs,
		MessageInfos:      file_proto_search_proto_msgTypes,
	}.Build()
	File_proto_search_proto = out.File
	file_proto_search_proto_rawDesc = nil
	file_proto_search_proto_goTypes = nil
	file_proto_search_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	EquipmentSearch(ctx context.Context, in *Search, opts ...grpc.CallOption) (SearchService_EquipmentSearchClient, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) EquipmentSearch(ctx context.Context, in *Search, opts ...grpc.CallOption) (SearchService_EquipmentSearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SearchService_serviceDesc.Streams[0], "/ahri_grpc.SearchService/EquipmentSearch", opts...)
	if err != nil {
		return nil, err
	}
	x := &searchServiceEquipmentSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SearchService_EquipmentSearchClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type searchServiceEquipmentSearchClient struct {
	grpc.ClientStream
}

func (x *searchServiceEquipmentSearchClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	EquipmentSearch(*Search, SearchService_EquipmentSearchServer) error
}

// UnimplementedSearchServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (*UnimplementedSearchServiceServer) EquipmentSearch(*Search, SearchService_EquipmentSearchServer) error {
	return status.Errorf(codes.Unimplemented, "method EquipmentSearch not implemented")
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_EquipmentSearch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Search)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SearchServiceServer).EquipmentSearch(m, &searchServiceEquipmentSearchServer{stream})
}

type SearchService_EquipmentSearchServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type searchServiceEquipmentSearchServer struct {
	grpc.ServerStream
}

func (x *searchServiceEquipmentSearchServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ahri_grpc.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EquipmentSearch",
			Handler:       _SearchService_EquipmentSearch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/search.proto",
}
